name: fer_mobile
description: "This project aims to develop a mobile application that is able to
  recognize users' facial expressions in real-time using Face Expression
  Recognition (FER) technology."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  audioplayers: ^5.2.1
  camera: ^0.10.5
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.8
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  get: ^4.7.2
  google_fonts: ^6.2.1
  google_ml_kit: ^0.20.0
  image: ^4.5.4
  intl: ^0.20.2
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/alert/
    - assets/image/
    - assets/model/
