name: fer_mobile
description: "This project aims to develop a mobile application that is able to recognize users' facial expressions in real-time using Face Expression Recognition (FER) technology."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  tflite_flutter: ^0.11.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
   - assets
