name: fer_mobile
description: "This project aims to develop a mobile application that is able to
  recognize users' facial expressions in real-time using Face Expression
  Recognition (FER) technology."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  sqflite: ^2.4.2
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8  
  convex_bottom_bar: ^3.2.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/alert/
    - assets/image/
    - assets/model/
